### PR TITLE
'Automatically Remove All Desktop Shortcuts' Option

### LINKED ISSUE #3321: Option to delete all desktop shortcuts
### Please confirm these before moving forward.

- [x] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [x] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29).
- [x] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29).

### Describe the improvement

The shortcut manager would be a lot easier to manage for me if I could just set it to always delete all desktop shortcuts. 

### Describe how this improvement could help users

I keep a clean desktop. I use no shortcuts, and the shortcut manager has the tendency to miss one or two. It might be that I'm not setting it correctly, but I have not gotten it to always delete all shortcuts. I've had this issue on three different PC's. Having to maintain a list of apps that don't keep shortcuts is superfluous for people like me, and confusing when all I want is no shortcuts. 

Thank you for your consideration.

### LINKED ISSUE #3369: [BUG] "Manage shortcuts" window too large on small screens with unavailable buttons
### Please confirm these before moving forward

- [x] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [x] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [x] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [x] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.6

### Windows version, edition, and architecture

Windows 10 & 11 (any version)

### Describe your issue

The "manage shortcuts" window is too large on small screens. Because of that, it exceeds the screen size, making most of the buttons unavailable.

### Steps to reproduce the issue

Open the "manage shortcuts" window on a small screen (e.g. either physically or with increased display DPI).

### UniGetUI Log

```text
N/A
```

### Package Managers Logs

```text
N/A
```

### Relevant information

_No response_

### Screenshots and videos

This is how the window looks one an 8.8" display with DPI set to 300%.

Image

### PR DESCRIPTION
**Pull request by mrixner**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#coding), and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**.
- [x] **Have you checked that there aren't other open [pull requests](https://github.com/marticliment/WingetUI/pulls) for the same changes?**
- [x] **Have you tested that the committed code can be executed without errors?**
- [x] **This PR is not composed of garbage changes used to farm GitHub activity to enter potential Crypto AirDrops.**
Any user suspected of farming GitHub activity with crypto purposes will get banned. Submitting broken code wastes the contributors' time, who have to spend their free time reviewing, fixing, and testing code that does not even compile breaks other features, or does not introduce any useful changes. I appreciate your understanding.
-----

This PR adds an option in the 'manage desktop shortcuts' dialog to automatically delete all desktop shortcuts when they're encountered. It does not delete shortcuts marked to not be deleted in the dialog.

-----
Closes #3321
Closes #3369

### CODE REVIEW

**Comment by marticliment** [comment]
Looks good. Will test and merge later

**Comment by marticliment** [comment]
Clicking "Manual Scan" with the new option enabled wipes all shortcuts out of existence. 
Please do check all possible risky scenarios before posting a PR

File: src/UniGetUI.PackageEngine.Operations/PackageOperations.cs [hunk 1]
```diff
@@ -154,7 +154,9 @@ protected override Task HandleSuccess()
 
             if (Settings.Get("AskToDeleteNewDesktopShortcuts"))
             {
-                DesktopShortcutsDatabase.TryRemoveNewShortcuts(DesktopShortcutsBeforeStart);
+                // If RemoveAllDesktopShortcuts is enabled, we don't care if the shortcuts were there before the oepration or not;
```
Comment (erwindon) [inline src/UniGetUI.PackageEngine.Operations/PackageOperations.cs]: oepration or operation?

**Review by marticliment — CHANGES_REQUESTED** [review]
@mrixner, I think it would make more sense to have two different methods, one to clean up the new shortcuts, and one to delete all shortcuts from the desktop; and then call them whenever they need to be calledd, instead of frankensteininga method that when passed an empty vector will do a thing or another, as this is very confusing and can very easily lead to confusion and chaos (as it already happened).

I think having more simple, do-one-thing-only methods is the way to go, because the code will be more maintainable in the future.

**Comment by mrixner** [comment]
I was going to try to see if I could fix #3369 as well, but I can no longer build UniGetUI after merging main into the branch.
image
I suspect it has something to do with the `Width="*"` column definitions not shrinking when the window does or `HorizontalAlignment="Stretch"` having a similar issue, but I'm not proficient enough in XAML to determine that without a working build.

Everything else works, though, and I tested all the cases I could think of.

**Comment by marticliment** [comment]
No, the issue you are seeing is different.
Go to Solution explorer -> Solution items -> Directory.build.props and there change the WindowsSdkVersion from X.X.X.56 to X.X.X.57 or viceversa
